/* Tested under SQLite, Brad Howard @ 22:28 on 2/28/2017 */

CREATE TABLE Walks 
(
	WID INTEGER PRIMARY KEY AUTOINCREMENT, /* MySQL -> AUTO_INCREMENT = 1 */
	Name VARCHAR(100) NOT NULL, 
	FullLocation VARCHAR(200) NOT NULL, 
	NumberOfLandMarks INTEGER, 
	WalkLength DOUBLE,
	IsOrder TINYINT(1), /* Boolean */
	WalkPreviewID INTEGER,
	PicID INTEGER,
	FOREIGN KEY (WalkPreviewID) REFERENCES WalkDescription(DesID),
	FOREIGN KEY (PicID) REFERENCES WalkImages(PicID)
);

CREATE TABLE LandMarks
(
	LID INTEGER PRIMARY KEY AUTOINCREMENT, /* MySQL -> AUTO_INCREMENT = 1 */
	Name VARCHAR(100) NOT NULL,
	Longitude DOUBLE, 
	Latitude DOUBLE, 
	NumberOfWalks INTEGER,
	Description INTEGER,
	QRCodeID INTEGER,
	PicID INTEGER,
	FOREIGN KEY (Description) REFERENCES LandMarkDescription(DesID),
	FOREIGN KEY (QRCodeID) REFERENCES QRCodes(PicID),
	FOREIGN KEY (PicID) REFERENCES LandMarkImages(PicID)
);

CREATE TABLE WalkLandMarks 
(
	WalkID INTEGER, 
	LandMarkID INTEGER, 
	PRIMARY KEY (WalkID, LandMarkID)
);

CREATE TABLE WalkImages 
(
	PicID INTEGER PRIMARY KEY AUTOINCREMENT, /* MySQL -> AUTO_INCREMENT = 1 */
	WID INTEGER, 
	FileLocation VARCHAR(200),
	FOREIGN KEY (WID) REFERENCES Walks(WID)
);

CREATE TABLE LandMarkImages 
(
	PicID INTEGER PRIMARY KEY AUTOINCREMENT, /* MySQL -> AUTO_INCREMENT = 1 */
	LID INTEGER,
	FileLocation VARCHAR(200), 
	FOREIGN KEY (LID) REFERENCES LandMarks(LID)
);

CREATE TABLE WalkDescription
(
	DesID INTEGER PRIMARY KEY AUTOINCREMENT,
	WID INTEGER,
	Description VARCHAR(1000),
	FOREIGN KEY (WID) REFERENCES Walks(WID)
);

CREATE TABLE LandMarkDescription
(
	DesID INTEGER PRIMARY KEY AUTOINCREMENT, /* MySQL -> AUTO_INCREMENT = 1 */
	LID INTEGER,
	WID INTEGER,
	Description VARCHAR(1000),
	FOREIGN KEY (LID) REFERENCES LandMarks(LID),
	FOREIGN KEY (WID) REFERENCES Walks(WID)
);

CREATE TABLE QRCodes
(
	QRCID INTEGER PRIMARY KEY AUTOINCREMENT, /* MySQL -> AUTO_INCREMENT = 1 */
	LID INTEGER,
	RawCode VARCHAR(625),
	FOREIGN KEY (LID) REFERENCES LandMarks(LID)
);